version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: 'production'
    versioning-strategy: 'increase-if-necessary'

groups:
  production-dependencies:
    dependency-type: 'production'
