version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dependabot/production-dependencies"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"
    groups:
      production-dependencies:
        dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dependabot/dev-dependencies"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "development"
    groups:
      dev-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dependabot/indirect-dependencies"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "indirect"
    groups:
      indirect-dependencies:
        patterns:
          - "*"
